<?php 

/*
Question 2
______________________
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  1 and 2, the first 10 terms will be:
*/

function fibonacci($max){
	$prev 	= 1;
	$totalEven  = 0;

	for ($i=0; $i <= $max;) { 

		$i = $prev + $i;
		$prev = $prev + $i; 

		if ($i % 2 == 0) {
			$totalEven = $totalEven + $i;
		}

		if ($prev % 2 == 0) {
			$totalEven = $totalEven + $prev;
		}
	}
	return $totalEven;
}

echo fibonacci(4000000);
